version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: starwars_postgres
    environment:
      POSTGRES_DB: starwars_db
      POSTGRES_USER: starwars_misbah
      POSTGRES_PASSWORD: misbah
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
